#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MOCK_PID_FILE="/tmp/slidebolt-mock.pid"
MOCK_LOG="/tmp/mock-server.log"

log() { echo -e "\033[0;32m[dev]\033[0m $1"; }
err() { echo -e "\033[0;31m[dev]\033[0m $1"; }

mock_start() {
    mock_stop

    log "Building mock server..."
    cd "$SCRIPT_DIR/mock"
    go build -o /tmp/slidebolt-mock-server server.go

    log "Starting mock server (random port, mDNS advertised)..."
    HA_TOKEN=$(cat "$SCRIPT_DIR/testconfig/token") /tmp/slidebolt-mock-server > "$MOCK_LOG" 2>&1 &
    echo $! > "$MOCK_PID_FILE"
    sleep 1

    if kill -0 "$(cat "$MOCK_PID_FILE")" 2>/dev/null; then
        local port
        port=$(grep -oP 'listening on :\K[0-9]+' "$MOCK_LOG" || echo "???")
        log "Mock server started (PID $(cat "$MOCK_PID_FILE"), port $port)"
    else
        err "Mock server failed to start"
        cat "$MOCK_LOG"
        return 1
    fi
}

mock_stop() {
    if [[ -f "$MOCK_PID_FILE" ]]; then
        local pid
        pid=$(cat "$MOCK_PID_FILE")
        if kill -0 "$pid" 2>/dev/null; then
            kill "$pid" 2>/dev/null || true
            log "Mock server stopped (PID $pid)"
        fi
        rm -f "$MOCK_PID_FILE"
    fi
    # Clean up any strays
    pkill -f slidebolt-mock-server 2>/dev/null || true
}

ha_start() {
    bash "$SCRIPT_DIR/test-ha.sh" start
}

ha_stop() {
    bash "$SCRIPT_DIR/test-ha.sh" stop
}

ha_fresh() {
    log "Clearing HA generated data (keeping auth baseline)..."
    ha_stop

    # Remove HA-generated storage files, keep auth/onboarding baseline
    local storage="$SCRIPT_DIR/testconfig/.storage"
    if [[ -d "$storage" ]]; then
        # These are generated by HA at runtime - safe to remove
        rm -f "$storage/core.config_entries" \
              "$storage/core.device_registry" \
              "$storage/core.entity_registry" \
              "$storage/core.restore_state" \
              "$storage/core.config" \
              "$storage/core.uuid" \
              "$storage/http" \
              "$storage/http.auth" \
              "$storage/trace.saved_traces" \
              "$storage/repairs.issue_registry"
        log "Cleared. Kept: auth, auth_provider.homeassistant, onboarding"
    fi
}

up() {
    ha_start
    log "Ready — HA: http://localhost:38123 | Mock: random port (mDNS)"
}

down() {
    ha_stop
    log "All stopped"
}

logs_cmd() {
    local target="${1:-all}"
    case "$target" in
        mock)
            tail -f "$MOCK_LOG"
            ;;
        ha)
            docker logs -f slidebolt-ha-dev
            ;;
        all)
            echo "=== MOCK SERVER ==="
            cat "$MOCK_LOG"
            echo ""
            echo "=== HA LOGS ==="
            docker logs slidebolt-ha-dev 2>&1 | tail -30
            ;;
    esac
}

case "${1:-}" in
    up)      up ;;
    down)    down ;;
    mock_stop)    mock_stop ;;
    mock_start)    mock_start ;;
    restart) down; up ;;
    fresh)   ha_fresh; up ;;
    logs)    logs_cmd "${2:-all}" ;;
    *)
        echo "Usage: $0 [up|down|restart|fresh|logs]"
        echo ""
        echo "  up           Start HA container"
        echo "  down         Stop both"
        echo "  restart      Stop + start HA"
        echo "  fresh        Clear HA data + start" 
        echo "  logs         Show all logs"
        echo "  logs mock    Tail mock server logs"
        echo "  logs ha      Tail HA container logs"
        exit 1
        ;;
esac
